services:
  - type: web
    name: pathhub
    env: node
    buildCommand: npm ci --production
    startCommand: npm start
    plan: free
    healthCheckPath: /
    region: oregon
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: /opt/render/project/data/pathhub.db
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1 