; PathHub Client Inno Setup Script
; Build with: iscc installer\pathhub-client.iss
; Prerequisite: client-app\dist\pathhub-client.exe must exist
;   (generated by `npm run build` in client-app, which runs pkg)

#define MyAppName "PathHub Client"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "PathHub"
#define MyAppURL "https://github.com/hiromps/PathHub"
#define MyAppExeName "pathhub-client.exe"

[Setup]
AppId={{C9B41E72-4F4A-4F4E-9F7A-3B1F2A8B0001}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
DefaultDirName={autopf}\PathHub
DefaultGroupName=PathHub
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=..\dist
OutputBaseFilename=PathHub-Setup-{#MyAppVersion}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={app}\{#MyAppExeName}

[Languages]
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "..\client-app\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\README.md"; DestDir: "{app}"; Flags: ignoreversion isreadme

[Registry]
; Protocol handler registration: HKCU\Software\Classes\pathhub
; Equivalent to client-app\install-protocol.js but declarative.
Root: HKCU; Subkey: "Software\Classes\pathhub"; ValueType: string; ValueName: ""; ValueData: "PathHub Protocol"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\pathhub"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\pathhub\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKCU; Subkey: "Software\Classes\pathhub\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"

[Run]
Filename: "https://github.com/hiromps/PathHub"; Description: "PathHub の使い方を見る"; Flags: shellexec postinstall skipifsilent unchecked

[Code]
function InitializeSetup(): Boolean;
begin
  Result := True;
end;
